list_subst:[cos(theta1) = c1, cos(theta2) = c2, cos(theta3) = c3, cos(theta4) = c4, cos(theta5) = c5, cos(theta6) = c6, sin(theta1) = s1, sin(theta2) = s2, sin(theta3) = s3, sin(theta4) = s4, sin(theta5) = s5, sin(theta6) = s6, cos(theta2 + theta1) = c12, sin(theta2 + theta1) = s12]$

rotx(th):=matrix(
	[1, 0, 0, 0],
	[0, cos(th), -sin(th), 0],
	[0, sin(th), cos(th), 0],
	[0, 0, 0, 1])$

roty(th):=matrix(
	[cos(th), 0, sin(th), 0],
	[0, 1, 0, 0],
	[-sin(th), 0, cos(th), 0],
	[0, 0, 0, 1])$

rotz(th):=matrix(
	[cos(th), -sin(th), 0, 0],
	[sin(th), cos(th), 0, 0],
	[0, 0, 1, 0],
	[0, 0, 0, 1])$

trans(x,y,z):=matrix(
	[1, 0, 0, x],
	[0, 1, 0, y],
	[0, 0, 1, z],
	[0, 0, 0, 1])$

dh(theta, a, d, alpha):=rotz(theta).trans(a, 0, d).rotx(alpha)$

getO(T):=submatrix(T, 1, 2, 3)$

getX(T):=submatrix(4, T, 2, 3, 4)$

getY(T):=submatrix(4, T, 1, 3, 4)$

getZ(T):=submatrix(4, T, 1, 2, 4)$

getR(T):=submatrix(4, T, 4)$

invT(Tij):=block(
	[Rji, Oji, Tji],
	Rji : transpose(submatrix(4, Tij, 4)),
	Oji : -Rji.submatrix(4, Tij, 1, 2, 3),
	Tji : addcol(Rji, Oji),
	Tji : addrow(Tji, [0, 0, 0, 1])
)$

mytrigsimp(T) := trigsimp(trigreduce(T))$
