######################################################################
# Automatically generated by qmake (2.01a) jeu. janv. 31 09:01:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arm.h \
           ball.h \
           coordinatesystem.h \
           glwidget.h \
           plane.h \
           tools.h \
           trajectory.h \
           window.h
SOURCES += arm.cpp \
           ball.cpp \
           coordinatesystem.cpp \
           glwidget.cpp \
           main.cpp \
           plane.cpp \
           tools.cpp \
           trajectory.cpp \
           window.cpp
           
QT += opengl
LIBS += -lglut
