######################################################################
# Automatically generated by qmake (2.01a) mar. janv. 22 12:30:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/include/

# Input
HEADERS += glwidget.h window.h \
    ball.h \
    ground.h \
    coordinatesystem.h
SOURCES += glwidget.cpp main.cpp window.cpp \
    ball.cpp \
    ground.cpp \
    coordinatesystem.cpp

QT           += opengl
LIBS += -lglut
CONFIG += ...
